name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Setup Pages
              uses: actions/configure-pages@v2

            - name: Cache Dependencies
              id: cache-dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{hashFiles('yarn.lock')}}-modules

            - name: Cache Lock
              id: cache-lock
              uses: actions/cache@v3
              with:
                  path: package-lock.json
                  key: ${{hashFiles('yarn.lock')}}-lock

            - name: install
              if: steps.cache-dependencies.outputs.cache-hit != 'true'
              run: yarn install --immutable --immutable-cache --check-cache

            - run: yarn build

            - name: Upload build artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  # Upload build directory
                  path: "./build"

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
