name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16.13.0"

            - name: Cache Dependencies
              id: cache-dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{hashFiles('package.json')}}-modules

            - name: Cache Lock
              id: cache-lock
              uses: actions/cache@v3
              with:
                  path: package-lock.json
                  key: ${{hashFiles('package.json')}}-lock

            - name: install
              if: steps.cache-dependencies.outputs.cache-hit != 'true'
              run: npm install

            - run: npm run build

            - uses: JamesIves/github-pages-deploy-action@4.1.8
              with:
                  branch: gh-pages
                  folder: build
                  single-commit: true
